<?php
/**
 * Price
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PlugAndTravel.BookingAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * Price Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Price implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Price';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'total_price_breakdown' => 'double[]',
        'total_taxes_breakdown' => 'double[]',
        'total_price_before_discount_break_down' => 'double[]',
        'commission_included' => 'bool'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'total_price_breakdown' => 'TotalPriceBreakdown',
        'total_taxes_breakdown' => 'TotalTaxesBreakdown',
        'total_price_before_discount_break_down' => 'TotalPriceBeforeDiscountBreakDown',
        'commission_included' => 'CommissionIncluded'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'total_price_breakdown' => 'setTotalPriceBreakdown',
        'total_taxes_breakdown' => 'setTotalTaxesBreakdown',
        'total_price_before_discount_break_down' => 'setTotalPriceBeforeDiscountBreakDown',
        'commission_included' => 'setCommissionIncluded'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'total_price_breakdown' => 'getTotalPriceBreakdown',
        'total_taxes_breakdown' => 'getTotalTaxesBreakdown',
        'total_price_before_discount_break_down' => 'getTotalPriceBeforeDiscountBreakDown',
        'commission_included' => 'getCommissionIncluded'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['total_price_breakdown'] = isset($data['total_price_breakdown']) ? $data['total_price_breakdown'] : null;
        $this->container['total_taxes_breakdown'] = isset($data['total_taxes_breakdown']) ? $data['total_taxes_breakdown'] : null;
        $this->container['total_price_before_discount_break_down'] = isset($data['total_price_before_discount_break_down']) ? $data['total_price_before_discount_break_down'] : null;
        $this->container['commission_included'] = isset($data['commission_included']) ? $data['commission_included'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['total_price_breakdown'] === null) {
            $invalid_properties[] = "'total_price_breakdown' can't be null";
        }
        if ($this->container['commission_included'] === null) {
            $invalid_properties[] = "'commission_included' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['total_price_breakdown'] === null) {
            return false;
        }
        if ($this->container['commission_included'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets total_price_breakdown
     * @return double[]
     */
    public function getTotalPriceBreakdown()
    {
        return $this->container['total_price_breakdown'];
    }

    /**
     * Sets total_price_breakdown
     * @param double[] $total_price_breakdown The index of element indicates the day offset (example: TotalPriceBreakdown[0] represent the charges for the first day )
     * @return $this
     */
    public function setTotalPriceBreakdown($total_price_breakdown)
    {
        $this->container['total_price_breakdown'] = $total_price_breakdown;

        return $this;
    }

    /**
     * Gets total_taxes_breakdown
     * @return double[]
     */
    public function getTotalTaxesBreakdown()
    {
        return $this->container['total_taxes_breakdown'];
    }

    /**
     * Sets total_taxes_breakdown
     * @param double[] $total_taxes_breakdown Has the same rule like TotalPriceBreakdown              Please note taxes are not included in price breakdown
     * @return $this
     */
    public function setTotalTaxesBreakdown($total_taxes_breakdown)
    {
        $this->container['total_taxes_breakdown'] = $total_taxes_breakdown;

        return $this;
    }

    /**
     * Gets total_price_before_discount_break_down
     * @return double[]
     */
    public function getTotalPriceBeforeDiscountBreakDown()
    {
        return $this->container['total_price_before_discount_break_down'];
    }

    /**
     * Sets total_price_before_discount_break_down
     * @param double[] $total_price_before_discount_break_down For future use.
     * @return $this
     */
    public function setTotalPriceBeforeDiscountBreakDown($total_price_before_discount_break_down)
    {
        $this->container['total_price_before_discount_break_down'] = $total_price_before_discount_break_down;

        return $this;
    }

    /**
     * Gets commission_included
     * @return bool
     */
    public function getCommissionIncluded()
    {
        return $this->container['commission_included'];
    }

    /**
     * Sets commission_included
     * @param bool $commission_included Indicate if your commission is already included in price. (Expedia for example)
     * @return $this
     */
    public function setCommissionIncluded($commission_included)
    {
        $this->container['commission_included'] = $commission_included;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


