<?php
/**
 * RoomRS
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PlugAndTravel.BookingAPI
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;

/**
 * RoomRS Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class RoomRS implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'RoomRS';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'code' => 'string',
        'name' => 'string',
        'hotel_code' => 'string',
        'provider_hotel_code' => 'string',
        'provider' => 'string',
        'tokens' => '\Swagger\Client\Model\Token[]',
        'occupancy' => '\Swagger\Client\Model\Occupancy',
        'price_changed' => 'bool',
        'new_price' => '\Swagger\Client\Model\Price',
        'currency' => 'string',
        'is_non_refubdable' => 'bool',
        'cancellation_policies' => '\Swagger\Client\Model\CancellationPolicy[]',
        'room_supplements' => '\Swagger\Client\Model\RoomSupplement[]',
        'person_supplements' => '\Swagger\Client\Model\PersonSupplement[]',
        'room_taxes' => '\Swagger\Client\Model\RoomTax[]',
        'essential_informations' => 'string[]',
        'meal' => '\Swagger\Client\Model\Meal'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'code' => 'Code',
        'name' => 'Name',
        'hotel_code' => 'HotelCode',
        'provider_hotel_code' => 'ProviderHotelCode',
        'provider' => 'Provider',
        'tokens' => 'Tokens',
        'occupancy' => 'Occupancy',
        'price_changed' => 'PriceChanged',
        'new_price' => 'NewPrice',
        'currency' => 'Currency',
        'is_non_refubdable' => 'IsNonRefubdable',
        'cancellation_policies' => 'CancellationPolicies',
        'room_supplements' => 'RoomSupplements',
        'person_supplements' => 'PersonSupplements',
        'room_taxes' => 'RoomTaxes',
        'essential_informations' => 'EssentialInformations',
        'meal' => 'Meal'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'code' => 'setCode',
        'name' => 'setName',
        'hotel_code' => 'setHotelCode',
        'provider_hotel_code' => 'setProviderHotelCode',
        'provider' => 'setProvider',
        'tokens' => 'setTokens',
        'occupancy' => 'setOccupancy',
        'price_changed' => 'setPriceChanged',
        'new_price' => 'setNewPrice',
        'currency' => 'setCurrency',
        'is_non_refubdable' => 'setIsNonRefubdable',
        'cancellation_policies' => 'setCancellationPolicies',
        'room_supplements' => 'setRoomSupplements',
        'person_supplements' => 'setPersonSupplements',
        'room_taxes' => 'setRoomTaxes',
        'essential_informations' => 'setEssentialInformations',
        'meal' => 'setMeal'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'code' => 'getCode',
        'name' => 'getName',
        'hotel_code' => 'getHotelCode',
        'provider_hotel_code' => 'getProviderHotelCode',
        'provider' => 'getProvider',
        'tokens' => 'getTokens',
        'occupancy' => 'getOccupancy',
        'price_changed' => 'getPriceChanged',
        'new_price' => 'getNewPrice',
        'currency' => 'getCurrency',
        'is_non_refubdable' => 'getIsNonRefubdable',
        'cancellation_policies' => 'getCancellationPolicies',
        'room_supplements' => 'getRoomSupplements',
        'person_supplements' => 'getPersonSupplements',
        'room_taxes' => 'getRoomTaxes',
        'essential_informations' => 'getEssentialInformations',
        'meal' => 'getMeal'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['code'] = isset($data['code']) ? $data['code'] : null;
        $this->container['name'] = isset($data['name']) ? $data['name'] : null;
        $this->container['hotel_code'] = isset($data['hotel_code']) ? $data['hotel_code'] : null;
        $this->container['provider_hotel_code'] = isset($data['provider_hotel_code']) ? $data['provider_hotel_code'] : null;
        $this->container['provider'] = isset($data['provider']) ? $data['provider'] : null;
        $this->container['tokens'] = isset($data['tokens']) ? $data['tokens'] : null;
        $this->container['occupancy'] = isset($data['occupancy']) ? $data['occupancy'] : null;
        $this->container['price_changed'] = isset($data['price_changed']) ? $data['price_changed'] : null;
        $this->container['new_price'] = isset($data['new_price']) ? $data['new_price'] : null;
        $this->container['currency'] = isset($data['currency']) ? $data['currency'] : null;
        $this->container['is_non_refubdable'] = isset($data['is_non_refubdable']) ? $data['is_non_refubdable'] : null;
        $this->container['cancellation_policies'] = isset($data['cancellation_policies']) ? $data['cancellation_policies'] : null;
        $this->container['room_supplements'] = isset($data['room_supplements']) ? $data['room_supplements'] : null;
        $this->container['person_supplements'] = isset($data['person_supplements']) ? $data['person_supplements'] : null;
        $this->container['room_taxes'] = isset($data['room_taxes']) ? $data['room_taxes'] : null;
        $this->container['essential_informations'] = isset($data['essential_informations']) ? $data['essential_informations'] : null;
        $this->container['meal'] = isset($data['meal']) ? $data['meal'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        if ($this->container['code'] === null) {
            $invalid_properties[] = "'code' can't be null";
        }
        if ($this->container['name'] === null) {
            $invalid_properties[] = "'name' can't be null";
        }
        if ($this->container['hotel_code'] === null) {
            $invalid_properties[] = "'hotel_code' can't be null";
        }
        if ($this->container['provider_hotel_code'] === null) {
            $invalid_properties[] = "'provider_hotel_code' can't be null";
        }
        if ($this->container['provider'] === null) {
            $invalid_properties[] = "'provider' can't be null";
        }
        if ($this->container['tokens'] === null) {
            $invalid_properties[] = "'tokens' can't be null";
        }
        if ($this->container['occupancy'] === null) {
            $invalid_properties[] = "'occupancy' can't be null";
        }
        if ($this->container['price_changed'] === null) {
            $invalid_properties[] = "'price_changed' can't be null";
        }
        if ($this->container['new_price'] === null) {
            $invalid_properties[] = "'new_price' can't be null";
        }
        if ($this->container['currency'] === null) {
            $invalid_properties[] = "'currency' can't be null";
        }
        if ($this->container['is_non_refubdable'] === null) {
            $invalid_properties[] = "'is_non_refubdable' can't be null";
        }
        if ($this->container['cancellation_policies'] === null) {
            $invalid_properties[] = "'cancellation_policies' can't be null";
        }
        if ($this->container['meal'] === null) {
            $invalid_properties[] = "'meal' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        if ($this->container['code'] === null) {
            return false;
        }
        if ($this->container['name'] === null) {
            return false;
        }
        if ($this->container['hotel_code'] === null) {
            return false;
        }
        if ($this->container['provider_hotel_code'] === null) {
            return false;
        }
        if ($this->container['provider'] === null) {
            return false;
        }
        if ($this->container['tokens'] === null) {
            return false;
        }
        if ($this->container['occupancy'] === null) {
            return false;
        }
        if ($this->container['price_changed'] === null) {
            return false;
        }
        if ($this->container['new_price'] === null) {
            return false;
        }
        if ($this->container['currency'] === null) {
            return false;
        }
        if ($this->container['is_non_refubdable'] === null) {
            return false;
        }
        if ($this->container['cancellation_policies'] === null) {
            return false;
        }
        if ($this->container['meal'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets code
     * @return string
     */
    public function getCode()
    {
        return $this->container['code'];
    }

    /**
     * Sets code
     * @param string $code Unique code that identifies the room
     * @return $this
     */
    public function setCode($code)
    {
        $this->container['code'] = $code;

        return $this;
    }

    /**
     * Gets name
     * @return string
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     * @param string $name
     * @return $this
     */
    public function setName($name)
    {
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets hotel_code
     * @return string
     */
    public function getHotelCode()
    {
        return $this->container['hotel_code'];
    }

    /**
     * Sets hotel_code
     * @param string $hotel_code
     * @return $this
     */
    public function setHotelCode($hotel_code)
    {
        $this->container['hotel_code'] = $hotel_code;

        return $this;
    }

    /**
     * Gets provider_hotel_code
     * @return string
     */
    public function getProviderHotelCode()
    {
        return $this->container['provider_hotel_code'];
    }

    /**
     * Sets provider_hotel_code
     * @param string $provider_hotel_code
     * @return $this
     */
    public function setProviderHotelCode($provider_hotel_code)
    {
        $this->container['provider_hotel_code'] = $provider_hotel_code;

        return $this;
    }

    /**
     * Gets provider
     * @return string
     */
    public function getProvider()
    {
        return $this->container['provider'];
    }

    /**
     * Sets provider
     * @param string $provider
     * @return $this
     */
    public function setProvider($provider)
    {
        $this->container['provider'] = $provider;

        return $this;
    }

    /**
     * Gets tokens
     * @return \Swagger\Client\Model\Token[]
     */
    public function getTokens()
    {
        return $this->container['tokens'];
    }

    /**
     * Sets tokens
     * @param \Swagger\Client\Model\Token[] $tokens
     * @return $this
     */
    public function setTokens($tokens)
    {
        $this->container['tokens'] = $tokens;

        return $this;
    }

    /**
     * Gets occupancy
     * @return \Swagger\Client\Model\Occupancy
     */
    public function getOccupancy()
    {
        return $this->container['occupancy'];
    }

    /**
     * Sets occupancy
     * @param \Swagger\Client\Model\Occupancy $occupancy
     * @return $this
     */
    public function setOccupancy($occupancy)
    {
        $this->container['occupancy'] = $occupancy;

        return $this;
    }

    /**
     * Gets price_changed
     * @return bool
     */
    public function getPriceChanged()
    {
        return $this->container['price_changed'];
    }

    /**
     * Sets price_changed
     * @param bool $price_changed Indicates if the room has the same price as requested one or price has changed
     * @return $this
     */
    public function setPriceChanged($price_changed)
    {
        $this->container['price_changed'] = $price_changed;

        return $this;
    }

    /**
     * Gets new_price
     * @return \Swagger\Client\Model\Price
     */
    public function getNewPrice()
    {
        return $this->container['new_price'];
    }

    /**
     * Sets new_price
     * @param \Swagger\Client\Model\Price $new_price New price, if price has changed
     * @return $this
     */
    public function setNewPrice($new_price)
    {
        $this->container['new_price'] = $new_price;

        return $this;
    }

    /**
     * Gets currency
     * @return string
     */
    public function getCurrency()
    {
        return $this->container['currency'];
    }

    /**
     * Sets currency
     * @param string $currency
     * @return $this
     */
    public function setCurrency($currency)
    {
        $this->container['currency'] = $currency;

        return $this;
    }

    /**
     * Gets is_non_refubdable
     * @return bool
     */
    public function getIsNonRefubdable()
    {
        return $this->container['is_non_refubdable'];
    }

    /**
     * Sets is_non_refubdable
     * @param bool $is_non_refubdable Indicates explicitly if the reservation can be refunded or not after booking
     * @return $this
     */
    public function setIsNonRefubdable($is_non_refubdable)
    {
        $this->container['is_non_refubdable'] = $is_non_refubdable;

        return $this;
    }

    /**
     * Gets cancellation_policies
     * @return \Swagger\Client\Model\CancellationPolicy[]
     */
    public function getCancellationPolicies()
    {
        return $this->container['cancellation_policies'];
    }

    /**
     * Sets cancellation_policies
     * @param \Swagger\Client\Model\CancellationPolicy[] $cancellation_policies
     * @return $this
     */
    public function setCancellationPolicies($cancellation_policies)
    {
        $this->container['cancellation_policies'] = $cancellation_policies;

        return $this;
    }

    /**
     * Gets room_supplements
     * @return \Swagger\Client\Model\RoomSupplement[]
     */
    public function getRoomSupplements()
    {
        return $this->container['room_supplements'];
    }

    /**
     * Sets room_supplements
     * @param \Swagger\Client\Model\RoomSupplement[] $room_supplements Is an extra service per room such as:  Disney tickets, airport transfer an so on.
     * @return $this
     */
    public function setRoomSupplements($room_supplements)
    {
        $this->container['room_supplements'] = $room_supplements;

        return $this;
    }

    /**
     * Gets person_supplements
     * @return \Swagger\Client\Model\PersonSupplement[]
     */
    public function getPersonSupplements()
    {
        return $this->container['person_supplements'];
    }

    /**
     * Sets person_supplements
     * @param \Swagger\Client\Model\PersonSupplement[] $person_supplements Is an extra service per person such as:  Disney tickets, airport transfer an so on.
     * @return $this
     */
    public function setPersonSupplements($person_supplements)
    {
        $this->container['person_supplements'] = $person_supplements;

        return $this;
    }

    /**
     * Gets room_taxes
     * @return \Swagger\Client\Model\RoomTax[]
     */
    public function getRoomTaxes()
    {
        return $this->container['room_taxes'];
    }

    /**
     * Sets room_taxes
     * @param \Swagger\Client\Model\RoomTax[] $room_taxes
     * @return $this
     */
    public function setRoomTaxes($room_taxes)
    {
        $this->container['room_taxes'] = $room_taxes;

        return $this;
    }

    /**
     * Gets essential_informations
     * @return string[]
     */
    public function getEssentialInformations()
    {
        return $this->container['essential_informations'];
    }

    /**
     * Sets essential_informations
     * @param string[] $essential_informations
     * @return $this
     */
    public function setEssentialInformations($essential_informations)
    {
        $this->container['essential_informations'] = $essential_informations;

        return $this;
    }

    /**
     * Gets meal
     * @return \Swagger\Client\Model\Meal
     */
    public function getMeal()
    {
        return $this->container['meal'];
    }

    /**
     * Sets meal
     * @param \Swagger\Client\Model\Meal $meal
     * @return $this
     */
    public function setMeal($meal)
    {
        $this->container['meal'] = $meal;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


